version: 1.15.0
language: cn
aomori_logo: /images/avatar.jpg
aomori_logo_typed_animated: true
aomori_menu:
  Home: /
  Archives: /archives
aomori_widgets:
  - toc # 文章导航
  - category  #文章分类
  - tag # 文章标签
  - recent_posts  # 最新文章
  - archive #文章归档
aomori_copyright: true # or false